Vagrant.configure("2") do |config|
  config.vm.define :vap_vm do |vap_vm|
    vap_vm.vm.box = "vap"
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../ansible/playbook.yml"
    #ansible.verbose = "vvv"
    ansible.sudo = true
  end
end
