---
    - name: apt update
      apt: upgrade=dist update_cache=yes

    - name: Install list of packages
      apt: pkg={{item}} state=installed
      with_items:
      - apache2
      - libapache2-mod-wsgi
      - python-pip

    - name: pip packages
      pip: name=Flask

    - name: Flask app directory
      file: path=/data/www/apps/flask_example/ state=directory mode=0755

# patch is brilliant but contained a relative paths bug @ version 1.91
# which is the latest version in the PPA. Easier to use copy until
# the fix filters through
#    - name: patch apache config
#      patch: src=files/apache_config.patch basedir=/etc/apache2/sites-available
#      notify:
#      - restart apache
    - name: copy apache config
      copy: src=files/apache_config_full dest=/etc/apache2/sites-available/000-default.conf
      notify:
      - restart apache

    - name: add flask app
      copy: src=files/flask_example.py dest=/data/www/apps/flask_example/
      notify:
      - restart apache

    - name: add flask wsgi handler
      copy: src=files/flask_example.wsgi dest=/data/www/apps/flask_example/
      notify:
      - restart apache

